# Generated by Django 3.2.9 on 2022-03-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0001_initial'),
        ('tags_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='comments',
            field=models.ManyToManyField(related_name='tags', to='comments_app.Comment'),
        ),
    ]
