# Generated by Django 4.0.1 on 2022-01-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0002_post_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
