# Generated by Django 4.0.1 on 2022-02-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
