# Generated by Django 3.2.9 on 2022-03-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0009_post_user'),
    ]

    operations = [
    ]
